### ISSUE TITLE
Yo we should meet up

### ISSUE THREAD

**Issue by lanmower** [gudrb33333/meta-world-client#1]
Looks like you're combining mediasoup and three.js, maybe we can work together! At the very least I can help you with english readmes and stuff...

https://discord.gg/GFtdS7WS

**Comment by gudrb33333** [comment]
> Looks like you're combining mediasoup and three.js, maybe we can work together! At the very least I can help you with english readmes and stuff...
> 
> https://discord.gg/GFtdS7WS

Sorry. I couldn't check the issue because I was working.

I'm working on my own right now, so it would be nice to have a friend to work with!

I recently finished a step work. 

It's not connected to the cdn yet, and there is a server in Seoul, so it might be slow, but take a look.

[https://meta-world.gudrb33333.click/room?user-type=guest](https://meta-world.gudrb33333.click/room?user-type=guest)

ps. If you check this post, I would appreciate it if you could reopen Discord because I don't know how to open it.

**Comment by lanmower** [comment]
Hi there, I see you're having some trouble with discord? Discord is a chat application where we hang out and talk about these things, you're welcome to drop in and talk to us whenever you want, if it would help 😄

Thank you for making contact, I'm quite excited about doing a project in this line...

Also, we can help you sort out some free serverspace to use for testing and stuff...

**Comment by gudrb33333** [comment]
I checked the invitation again and entered!

I'm using Amazon server right now, but I don't think it can be maintained.

I would really appreciate it if you could point me to a spare server I can use.

English is not my mother tongue, so communication may be a little inconvenient, but I will try  :)

**Comment by lanmower** [comment]
it seems like you're already there :)
